UserAccount/remkit/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from users import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/', views.special, name='special')

]

UserAccount/users/urls.py
from django.conf.urls import url
from users import views


# Template URLS!

app_name = 'users'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login')
]

UserAccount/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional classes

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

UserAccount/users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import UserProfileInfo


class UserForm(forms.ModelForm):  # base class
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):  # inherit from (forms.ModelsForm)

    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

UserAccount/users/views.py
from django.shortcuts import render
from users.forms import UserForm, UserProfileInfoForm
# Create your views here.

#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
# from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'users/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in , Nice!! ")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

                profile.save()
                registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'users/registration.html',
     {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE!!")
        else:
            print("Someone Try to login and Failed!!")
            print("Username: {} and Password {} ".format(username, password))
            return HttpResponse("Invalid login details!")
    else:
        return render(request, 'users/login.html',{})

UserAccount/users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base Title</title>
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body>
    <nav class='navbar navbar-default navbar-static-top'>
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'users:register' %}">Register</a></li>

            {% if user.is_authenticated %}
                <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'users:user_login' %}">Login</a> </li>
            {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>


</body>

</html>

UserAccount/users/templates/users/index.html
{% extends "users/base.html" %}

{%block body %}

<div class="jumbotron">
    <h1>Django Index Page</h1>
</div>
{% endblock %}

UserAccount/users/templates/users/login.html
{% extends 'users/base.html'%}
{% block body %}

  <div class="jumbotron">
      <h1>Please Login</h1>
      <form action="{% url 'users:user_login' %}" method="post">
          {% csrf_token %}
          <label for="username">UserName: </label>
          <input type="text" name="username" placeholder="Enter UserName">

          <label for="password">Password: </label>
          <input type="password" name="password" placeholder="Enter Password">

          <input type="submit" name="" value="Login">

      </form>
  </div>

{% endblock %}

UserAccount/users/templates/users/registration.html
{% extends 'users/base.html' %}

{% block body %}

<div class="jumbotron">
    {% if registered %}
    <h1>Thankyou for registering!!!</h1>
    {% else %}
    <h1>Register Here</h1>
    <h3>Fill Out the Form:</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <input type="submit" value="Register"/>
    </form>

    {% endif %}

</div>
{% endblock %}